version: '3'
services:
  db:
    image: postgres:10.5-alpine
    restart: always
    volumes:
      - data-flaskapi:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: admin

  web:
    container_name: flaskapi
    build: .
    image: flaskapi
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
  redis:
    image: redis
volumes:
  data-flaskapi:
    external: true
